config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'blogs#index' 
  resources :blogs do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @blogs = Blog.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(image: blog_params[:image], text: blog_params[:text], user_id: current_user.id)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @comments = @blog.comments.includes(:user)
  end

  private
  def blog_params
    params.permit(:image, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
   comment = Comment.create(text: comment_params[:text], blog_id: comment_params[:blog_id], user_id: current_user.id)
    redirect_to "/blogs/#{comment.blog.id}"  
  end

  private
  def comment_params
    params.permit(:text, :blog_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @blogs = user.blogs.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<div class="card large">
<div class="content_post" style="background-image: url(<%= blog.image %>);">
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to "詳細", blog_path(blog.id), method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == blog.user_id %>
        <li>
          <%= link_to '編集', "/blogs/#{blog.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/blogs/#{blog.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <span class="name">
    <a href="/users/<%= blog.user_id %>">
      <span>投稿者</span><%= blog.user.nickname %>
    </a>
  </span>
  </div>
    <%= simple_format(blog.text) %>
</div>

app/views/blogs/create.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/blogs">投稿一覧へ戻る</a>
    </div>
 

app/views/blogs/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/blogs/edit.html.erb
<div class="contents row">
    <%= form_with(model: @blog, local: true ) do %>
      <h3>
        編集する
      </h3>
      <input placeholder="Image Url" type="text" name="image" value="<%= @blog.image %>" autofocus="true">
      <textarea cols="30" name="text" placeholder="text" rows="10"><%= @blog.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>

app/views/blogs/index.html.erb
<div class="contents row">
  <% @blogs.each do |blog| %>
    <%= render partial: "blog", locals: { blog: blog } %>
  <% end %>
  <%= paginate(@blogs) %>
</div>

app/views/blogs/new.html.erb
<div class="contents row">
  <div class="container">
  <%= form_with(model: @blog, local: true) do %>
    <h3>
      投稿する
    </h3>
    <input placeholder="Image URL" type="text" name="image" autofocus="true">
    <textarea placeholder="text" name="text" cols="30" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @blog.image %>);">
    <% if user_signed_in? && current_user.id == @blog.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/blogs/#{@blog.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/blogs/#{@blog.id}", method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <%= simple_format(@blog.text) %>
    <span class="name">
      <a href="/users/<%= @blog.user.id %>">
        <span>投稿者</span><%= @blog.user.nickname %>
      </a>
    </span>
  </div>
   <div class="container"> 
    <!-- ここからフォーム -->
    <% if current_user %>
      <%= form_tag("/blogs/#{@blog.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
        <div class="comments">   
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <div class="row">
      <div class="col s12 m5">
        <div class="card-panel teal">
          <span class="white-text">
            <%= comment.text %>
          </span>
        </div>
      </div>
    </div>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>minimini-app</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
          <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

 <body> 
 <div class="progress">
      <div class="indeterminate"></div>
  </div>
  <header class="header">
    <nav class="teal darken-4">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">minimini-app</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                <a class="post" href="/blogs/new">投稿する</a>
              </li>
            </ul>
          </span>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
        </div>
      <% end %>
     </ul>
  </div>
  </header>
 
    <%= yield %>

    <footer>
      <p>
        Copyright 
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @blogs.each do |blog| %>
    <%= render partial: "blogs/blog", locals: { blog: blog } %>
  <% end %>
  <%= paginate(@blogs) %>
</div>